name: yume-linux

on:
  push:
    branches: [ develop ]
    paths:
      - '**.cpp'
      - '**.h'
      - 'CMakeLists.txt'
      - '.github/workflows/yume-linux.yml'
      - 'program_info/**'
      - 'launcher/resources/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies (Qt6)
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake ninja-build pkg-config \
            qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools \
            libqt6core5compat6-dev qt6-networkauth-dev extra-cmake-modules \
            zlib1g-dev libgl1-mesa-dev openjdk-17-jdk \
            libxkbcommon-dev vulkan-headers libvulkan-dev

      - name: Configure (CMake + Ninja)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yume-linux
          path: build/**
